# Generated by Django 2.1.1 on 2019-06-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190620_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_column='姓名', max_length=20, verbose_name='姓名'),
        ),
    ]
